### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by LeeBergstrand**
Add various requested changes to dev suggested during the pull request https://github.com/rotary-genomics/rotary/pull/94

### CODE REVIEW

**Comment by LeeBergstrand** [comment]
@jmtsuji POLCA leaves an entire folder full of output files not specified in the rule output. I'm considering having it delete its entire folder using temp. See: https://github.com/rotary-genomics/rotary/issues/92

**Comment by LeeBergstrand** [comment]
> @jmtsuji POLCA leaves an entire folder full of output files not specified in the rule output. I'm considering having it delete its entire folder using temp. See: #92

For example I'm find the following files in the polca directory: 

```
lrwxrwxrwx 1 lbergstrand lbergstrand   39 Dec 15 15:48 blam_polca.fasta -> blam_polypolish.fasta.PolcaCorrected.fa
-rw-rw-r-- 1 lbergstrand lbergstrand  18K Nov 14 02:01 blam_polypolish.fasta.alignSorted.bam.bai
-rw-rw-r-- 1 lbergstrand lbergstrand   48 Nov 14 02:01 blam_polypolish.fasta.batches
-rw-rw-r-- 1 lbergstrand lbergstrand   12 Nov 14 02:00 blam_polypolish.fasta.bwa.amb
-rw-rw-r-- 1 lbergstrand lbergstrand   43 Nov 14 02:00 blam_polypolish.fasta.bwa.ann
-rw-rw-r-- 1 lbergstrand lbergstrand 5.5M Nov 14 02:00 blam_polypolish.fasta.bwa.bwt
-rw-rw-r-- 1 lbergstrand lbergstrand 1.4M Nov 14 02:00 blam_polypolish.fasta.bwa.pac
-rw-rw-r-- 1 lbergstrand lbergstrand 2.8M Nov 14 02:00 blam_polypolish.fasta.bwa.sa
-rw-rw-r-- 1 lbergstrand lbergstrand    0 Nov 14 02:01 blam_polypolish.fasta.fix.success
-rw-rw-r-- 1 lbergstrand lbergstrand    0 Nov 14 02:00 blam_polypolish.fasta.index.success
-rw-rw-r-- 1 lbergstrand lbergstrand    0 Nov 14 02:01 blam_polypolish.fasta.map.success
-rw-rw-r-- 1 lbergstrand lbergstrand    9 Nov 14 02:01 blam_polypolish.fasta.names
-rw-rw-r-- 1 lbergstrand lbergstrand 5.5M Nov 14 02:01 blam_polypolish.fasta.PolcaCorrected.fa
-rw-rw-r-- 1 lbergstrand lbergstrand  123 Nov 14 02:01 blam_polypolish.fasta.report
-rw-rw-r-- 1 lbergstrand lbergstrand    0 Nov 14 02:01 blam_polypolish.fasta.report.success
-rw-rw-r-- 1 lbergstrand lbergstrand    0 Nov 14 02:01 blam_polypolish.fasta.sort.success
-rw-rw-r-- 1 lbergstrand lbergstrand  18K Nov 14 02:01 blam_polypolish.fasta.vcf
-rw-rw-r-- 1 lbergstrand lbergstrand    0 Nov 14 02:01 blam_polypolish.fasta.vc.success
```

**Review by jmtsuji — APPROVED** [review]
Looks great -- thanks so much for making these changes! I just cleaned up the description of the human genome accession in the config, but otherwise, everything else looks good. Merging in.

**Comment by jmtsuji** [comment]
P.S. Let's continue to discuss POLCA in #100 -- agreed we should think on this more.

**Pull request merged**
